# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameRunning.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class GameUi_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(756, 384)
        Form.setStyleSheet("background-color: rgb(154, 244, 244);")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 260, 231, 41))
        self.progressBar.setStyleSheet("selection-color: rgb(255, 170, 255);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(Form)
        self.progressBar_2.setGeometry(QtCore.QRect(450, 260, 241, 41))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 190, 241, 33))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 36pt \"Stencil\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(450, 190, 241, 33))
        self.label_2.setStyleSheet("font: 36pt \"Stencil\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(320, 40, 91, 91))
        self.label_3.setMaximumSize(QtCore.QSize(291, 231))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 48pt \"Stencil\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Player One"))
        self.label_2.setText(_translate("Form", "Player Two"))
        self.label_3.setText(_translate("Form", "Go!"))
