# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SaveDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(344, 329)
        Form.setStyleSheet("background-color: rgb(154, 244, 244);")
        self.Score = QtWidgets.QLabel(Form)
        self.Score.setGeometry(QtCore.QRect(20, 60, 116, 33))
        self.Score.setStyleSheet("font: 20pt \"Stencil\";")
        self.Score.setObjectName("Score")
        self.StudentName = QtWidgets.QLabel(Form)
        self.StudentName.setGeometry(QtCore.QRect(20, 110, 116, 33))
        self.StudentName.setStyleSheet("font: 20pt \"Stencil\";")
        self.StudentName.setObjectName("StudentName")
        self.School = QtWidgets.QLabel(Form)
        self.School.setGeometry(QtCore.QRect(20, 160, 116, 33))
        self.School.setStyleSheet("font: 20pt \"Stencil\";")
        self.School.setObjectName("School")
        self.StudentNameInput = QtWidgets.QLineEdit(Form)
        self.StudentNameInput.setGeometry(QtCore.QRect(150, 120, 111, 21))
        self.StudentNameInput.setObjectName("StudentNameInput")
        self.SchoolInput = QtWidgets.QLineEdit(Form)
        self.SchoolInput.setGeometry(QtCore.QRect(150, 170, 111, 21))
        self.SchoolInput.setObjectName("SchoolInput")
        self.Save = QtWidgets.QPushButton(Form)
        self.Save.setGeometry(QtCore.QRect(140, 220, 144, 41))
        self.Save.setStyleSheet("font: 20pt \"Stencil\";")
        self.Save.setObjectName("Save")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 60, 71, 20))
        self.label.setStyleSheet("font: 20pt \"Stencil\";")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Score.setText(_translate("Form", "Score"))
        self.StudentName.setText(_translate("Form", "Name"))
        self.School.setText(_translate("Form", "School"))
        self.Save.setText(_translate("Form", "Save"))
        self.label.setText(_translate("Form", "Score"))
